@host = http://localhost
@port = 3000
@api = {{host}}:{{port}}/auth

### sing up
POST {{api}}/singup
Content-Type: application/json

{
  "email": "d22ani541961@gmail.com",
  "password": "1234abCD!",
  "firstName": "dani"
}

### sing in
POST {{api}}/singin
Content-Type: application/json

{
  "email": "d22ani541961@gmail.com",
  "password": "1234abCD!"
}
