version: "3.3"

services:
  mysqldb:
    image: mysql
    restart: always #on-failure:5
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=menu
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql

  api:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=menu
    depends_on:
      - mysqldb
      
  vite:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]

volumes:
  db:
