@host = http://localhost
@port = 3000
@api = {{host}}:{{port}}
### get all users
GET {{api}}/api/user
### create a user
POST {{api}}/api/user
Content-Type: application/json

{
  "user_id": 1,
  "email": "dani54196@gmail.com",
  "password": "contra1@",
  "firstName": "Daniel",
  "lastName": "Cardozo"
}